steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/hephae-co-dev/hephae-website', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/hephae-co-dev/hephae-website']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'hephae-co-genai-consulting'
  - '--image'
  - 'gcr.io/hephae-co-dev/hephae-website'
  - '--region'
  - 'us-west1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
images:
- 'gcr.io/hephae-co-dev/hephae-website'
